// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtKHwV_0a9eDEtzwUUhq4ESn4adoJWcqk',
    appId: '1:686701251370:web:e572c8f761132052c96c53',
    messagingSenderId: '686701251370',
    projectId: 'trashbookingapp',
    authDomain: 'trashbookingapp.firebaseapp.com',
    storageBucket: 'trashbookingapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWuUNJrmlL8i77NwcZQpEPWRrsQILyXdM',
    appId: '1:686701251370:android:8114f4775904e9b8c96c53',
    messagingSenderId: '686701251370',
    projectId: 'trashbookingapp',
    storageBucket: 'trashbookingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGczH__DZmp2xIb8T6P8GmgnSqVQSMRE',
    appId: '1:686701251370:ios:98c2e85ac484063bc96c53',
    messagingSenderId: '686701251370',
    projectId: 'trashbookingapp',
    storageBucket: 'trashbookingapp.firebasestorage.app',
    iosBundleId: 'com.example.bookingDonRac',
  );
}
